var cardSet = {
  title: "League of Legends champion primary damage flashcards",
  cards: [
    { text: "What is the primary damage type of Aatrox?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Ahri?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Akali?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Alistar?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Amumu?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Anivia?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Annie?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Ashe?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Aurelion Sol?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Azir?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Bard?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Blitzcrank?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Brand?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Braum?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Caitlyn?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Cassiopeia?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Cho'Gath?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Corki?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Darius?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Diana?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Dr. Mundo?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Draven?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Ekko?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Elise?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Evelynn?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Ezreal?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Fiddlesticks?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Fiora?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Fizz?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Galio?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Gangplank?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Garen?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Gnar (Mega)?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Gnar (Mini)?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Gragas?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Graves?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Hecarim?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Heimerdinger?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Illaoi?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Irelia?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Ivern?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Janna?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Jarvan IV?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Jax?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Jayce?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Jhin?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Jinx?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Kalista?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Karma?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Karthus?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Kassadin?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Katarina?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Kayle?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Kennen?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Kha'Zix?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Kindred?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Kog'Maw?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of LeBlanc?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Lee Sin?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Leona?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Lissandra?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Lucian?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Lulu?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Lux?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Malphite?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Malzahar?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Maokai?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Master Yi?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Miss Fortune?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Mordekaiser?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Morgana?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Nami?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Nasus?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Nautilus?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Nidalee?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Nocturne?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Nunu?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Olaf?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Orianna?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Pantheon?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Poppy?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Quinn?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Rammus?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Rek'Sai?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Renekton?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Rengar?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Riven?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Rumble?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Ryze?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Sejuani?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Shaco?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Shen?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Shyvana?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Singed?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Sion?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Sivir?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Skarner?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Sona?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Soraka?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Swain?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Syndra?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Tahm Kench?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Taliyah?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Talon?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Taric?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Teemo?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Thresh?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Tristana?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Trundle?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Tryndamere?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Twisted Fate?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Twitch?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Udyr?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Urgot?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Varus?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Vayne?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Veigar?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Vel'Koz?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Vi?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Viktor?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Vladimir?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Volibear?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Warwick?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Wukong?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Xerath?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Xin Zhao?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Yasuo?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Yorick?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of Zac?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Zed?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of Ziggs?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Zilean?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of Zyra?", answer: "Magic (AP)" }
  ]
};