var cardSet = {
  title: "League of Legends champion primary damage flashcards",
  cards: [
    { text: "What is the primary damage type of \nAatrox?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nAhri?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nAkali?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nAlistar?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nAmumu?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nAnivia?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nAnnie?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nAshe?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nAurelion Sol?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nAzir?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nBard?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nBlitzcrank?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nBrand?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nBraum?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nCaitlyn?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nCassiopeia?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nCho'Gath?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nCorki?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nDarius?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nDiana?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nDr. Mundo?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nDraven?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nEkko?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nElise?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nEvelynn?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nEzreal?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nFiddlesticks?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nFiora?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nFizz?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nGalio?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nGangplank?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nGaren?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nGnar (Mega)?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nGnar (Mini)?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nGragas?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nGraves?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nHecarim?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nHeimerdinger?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nIllaoi?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nIrelia?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nIvern?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nJanna?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nJarvan IV?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nJax?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nJayce?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nJhin?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nJinx?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nKalista?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nKarma?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nKarthus?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nKassadin?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nKatarina?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nKayle?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nKennen?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nKha'Zix?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nKindred?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nKog'Maw?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nLeBlanc?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nLee Sin?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nLeona?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nLissandra?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nLucian?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nLulu?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nLux?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nMalphite?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nMalzahar?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nMaokai?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nMaster Yi?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nMiss Fortune?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nMordekaiser?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nMorgana?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nNami?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nNasus?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nNautilus?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nNidalee?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nNocturne?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nNunu?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nOlaf?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nOrianna?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nPantheon?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nPoppy?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nQuinn?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nRammus?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nRek'Sai?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nRenekton?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nRengar?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nRiven?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nRumble?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nRyze?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nSejuani?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nShaco?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nShen?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nShyvana?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nSinged?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nSion?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nSivir?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nSkarner?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nSona?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nSoraka?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nSwain?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nSyndra?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nTahm Kench?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nTaliyah?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nTalon?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nTaric?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nTeemo?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nThresh?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nTristana?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nTrundle?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nTryndamere?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nTwisted Fate?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nTwitch?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nUdyr?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nUrgot?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nVarus?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nVayne?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nVeigar?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nVel'Koz?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nVi?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nViktor?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nVladimir?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nVolibear?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nWarwick?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nWukong?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nXerath?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nXin Zhao?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nYasuo?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nYorick?", answer: "Mixed (AD/AP)" },
    { text: "What is the primary damage type of \nZac?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nZed?", answer: "Physical (AD)" },
    { text: "What is the primary damage type of \nZiggs?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nZilean?", answer: "Magic (AP)" },
    { text: "What is the primary damage type of \nZyra?", answer: "Magic (AP)" }
  ]
};